---
apiVersion: v1
kind: Service
metadata:
  name: proxmox-external
  namespace: korczewski-infra
  labels:
    app.kubernetes.io/part-of: korczewski
    tier: infrastructure
spec:
  type: ClusterIP
  ports:
    - port: 8006
      targetPort: 8006
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox-external
  namespace: korczewski-infra
subsets:
  - addresses:
      - ip: 10.0.0.7
    ports:
      - port: 8006
        protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: proxmox
  namespace: korczewski-infra
  labels:
    app.kubernetes.io/part-of: korczewski
    tier: infrastructure
spec:
  routes:
    - match: Host(`proxmox.korczewski.de`)
      kind: Rule
      services:
        - name: proxmox-external
          port: 8006
          scheme: https
      middlewares:
        - name: proxmox-auth-chain
  tls: {}
