declare const styles: {
  readonly app: string
  readonly header: string
  readonly headerContent: string
  readonly logo: string
  readonly main: string
  readonly container: string
  readonly grid: string
  readonly gridCols1: string
  readonly gridCols2: string
  readonly gridCols3: string
  readonly gridCols4: string
  readonly textCenter: string
  readonly textLeft: string
  readonly textRight: string
  readonly flex: string
  readonly flexCol: string
  readonly flexRow: string
  readonly flexWrap: string
  readonly itemsCenter: string
  readonly justifyCenter: string
  readonly justifyBetween: string
  readonly justifyEnd: string
  readonly gapSm: string
  readonly gapMd: string
  readonly gapLg: string
  readonly wFull: string
  readonly hFull: string
  readonly minHFull: string
  readonly rounded: string
  readonly roundedLg: string
  readonly roundedXl: string
  readonly shadow: string
  readonly shadowLg: string
  readonly transition: string
  readonly transitionFast: string
  readonly button: string
  readonly buttonSecondary: string
  readonly buttonOutline: string
  readonly card: string
  readonly spinner: string
  readonly loading: string
  readonly loadingSpinner: string
  readonly error: string
  readonly success: string
  readonly warning: string
}

export default styles 