---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: korczewski-infra
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "suaEsyKdILERi2Cp87XrMMD3HeVpZmBO"
  POSTGRES_DB: "postgres"
  AUTH_DB_PASSWORD: "2e4c28977e4e86afcaa485105ab0b53d"
  L2P_DB_PASSWORD: "23d13a56cfee5d0c5f9060fc62ab4a6d"
  SHOP_DB_PASSWORD: "2e67a4d8576773457fcaac19b3de8b1c"
  ARENA_DB_PASSWORD: "a7f3c2d9e1b84f6590d2ca7381ee4b27"
  VIDEOVAULT_DB_PASSWORD: "d5cd9488c0f39eef9d84903e3625b861"
