---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: korczewski-infra
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "wmF1ijSEcC5Rs5HhwMSWDJ5plKwE7Wxs"
  POSTGRES_DB: "postgres"
  AUTH_DB_PASSWORD: "kA7gUzWijrd3gPuSqxInVAZlr8os5H7P"
  L2P_DB_PASSWORD: "8vFDMg6Zy1qtZSkIDUTFDKtppehjL9Ob"
  SHOP_DB_PASSWORD: "PZgnM2if4Pww8lOeBvGiYktdlNSp2uSV"
  VIDEOVAULT_DB_PASSWORD: "iUICdVBPGIrWzdVc9zPT1MW0W7h741iG"
