import { jest } from '@jest/globals'

const mockUseVisualFeedback = {
  animateModal: jest.fn(),
  animateButton: jest.fn(),
  animateProgress: jest.fn(),
  animateScore: jest.fn(),
  animateTimer: jest.fn(),
  shakeElement: jest.fn(),
  pulseElement: jest.fn(),
  highlightElement: jest.fn(),
  fadeElement: jest.fn(),
  slideInElement: jest.fn(),
  slideOutElement: jest.fn(),
  bounceElement: jest.fn(),
  flashElement: jest.fn(),
  spinElement: jest.fn(),
  zoomElement: jest.fn(),
  flipElement: jest.fn(),
  triggerConfetti: jest.fn(),
  triggerParticles: jest.fn(),
  triggerRipple: jest.fn(),
  triggerWave: jest.fn(),
  triggerGlow: jest.fn(),
  triggerSparkle: jest.fn(),
  triggerFirework: jest.fn(),
  triggerStarburst: jest.fn(),
  triggerSnowfall: jest.fn(),
  triggerRain: jest.fn(),
  triggerLightning: jest.fn(),
  triggerEarthquake: jest.fn(),
  triggerVibrate: jest.fn(),
  triggerShake: jest.fn(),
  triggerPulse: jest.fn(),
  triggerBounce: jest.fn(),
  triggerFadeIn: jest.fn(),
  triggerFadeOut: jest.fn(),
  triggerSlideIn: jest.fn(),
  triggerSlideOut: jest.fn(),
  triggerZoomIn: jest.fn(),
  triggerZoomOut: jest.fn(),
  triggerFlipIn: jest.fn(),
  triggerFlipOut: jest.fn(),
  triggerPopIn: jest.fn(),
  triggerPopOut: jest.fn(),
  triggerSquash: jest.fn(),
  triggerStretch: jest.fn(),
  triggerWobble: jest.fn(),
  triggerJiggle: jest.fn(),
  triggerTada: jest.fn(),
  triggerSwing: jest.fn(),
  triggerHinge: jest.fn(),
  triggerRollIn: jest.fn(),
  triggerRollOut: jest.fn(),
}

export const useVisualFeedback = jest.fn(() => mockUseVisualFeedback)
export { mockUseVisualFeedback }
