import { vi } from 'vitest'

const mockUseVisualFeedback = {
  animateModal: vi.fn(),
  animateButton: vi.fn(),
  animateProgress: vi.fn(),
  animateScore: vi.fn(),
  animateTimer: vi.fn(),
  shakeElement: vi.fn(),
  pulseElement: vi.fn(),
  highlightElement: vi.fn(),
  fadeElement: vi.fn(),
  slideInElement: vi.fn(),
  slideOutElement: vi.fn(),
  bounceElement: vi.fn(),
  flashElement: vi.fn(),
  spinElement: vi.fn(),
  zoomElement: vi.fn(),
  flipElement: vi.fn(),
  triggerConfetti: vi.fn(),
  triggerParticles: vi.fn(),
  triggerRipple: vi.fn(),
  triggerWave: vi.fn(),
  triggerGlow: vi.fn(),
  triggerSparkle: vi.fn(),
  triggerFirework: vi.fn(),
  triggerStarburst: vi.fn(),
  triggerSnowfall: vi.fn(),
  triggerRain: vi.fn(),
  triggerLightning: vi.fn(),
  triggerEarthquake: vi.fn(),
  triggerVibrate: vi.fn(),
  triggerShake: vi.fn(),
  triggerPulse: vi.fn(),
  triggerBounce: vi.fn(),
  triggerFadeIn: vi.fn(),
  triggerFadeOut: vi.fn(),
  triggerSlideIn: vi.fn(),
  triggerSlideOut: vi.fn(),
  triggerZoomIn: vi.fn(),
  triggerZoomOut: vi.fn(),
  triggerFlipIn: vi.fn(),
  triggerFlipOut: vi.fn(),
  triggerPopIn: vi.fn(),
  triggerPopOut: vi.fn(),
  triggerSquash: vi.fn(),
  triggerStretch: vi.fn(),
  triggerWobble: vi.fn(),
  triggerJiggle: vi.fn(),
  triggerTada: vi.fn(),
  triggerSwing: vi.fn(),
  triggerHinge: vi.fn(),
  triggerRollIn: vi.fn(),
  triggerRollOut: vi.fn(),
}

export const useVisualFeedback = vi.fn(() => mockUseVisualFeedback)
export { mockUseVisualFeedback }
