-- =============================================================================
-- CAMPAIGN SOCIAL — Penpal, teacher classes, assignments, session reports, custom quests
-- =============================================================================
-- Extends campaign schema with social/AI learning systems.
-- Run against: arena_db as arena_user (or postgres superuser)
-- =============================================================================

-- =============================================================================
-- PENPAL LETTERS (incoming from NPC + player replies)
-- =============================================================================
CREATE TABLE IF NOT EXISTS campaign_penpal_letters (
    id SERIAL PRIMARY KEY,
    player_id INTEGER NOT NULL REFERENCES campaign_players(id) ON DELETE CASCADE,
    country_id VARCHAR(60) NOT NULL,
    penpal_npc_id VARCHAR(100) NOT NULL,
    direction VARCHAR(10) NOT NULL CHECK (direction IN ('incoming', 'reply')),
    subject VARCHAR(200),
    body TEXT NOT NULL,
    vocab_highlighted JSONB DEFAULT '[]'::jsonb,
    grade_json JSONB,          -- Filled by ClosedPaw for player replies
    respect_earned INTEGER DEFAULT 0,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_penpal_player ON campaign_penpal_letters(player_id, country_id);

-- =============================================================================
-- TEACHER CLASSES
-- =============================================================================
CREATE TABLE IF NOT EXISTS campaign_classes (
    id SERIAL PRIMARY KEY,
    teacher_auth_user_id INTEGER NOT NULL,
    name VARCHAR(200) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- CLASS MEMBERSHIP
-- =============================================================================
CREATE TABLE IF NOT EXISTS campaign_class_members (
    id SERIAL PRIMARY KEY,
    class_id INTEGER NOT NULL REFERENCES campaign_classes(id) ON DELETE CASCADE,
    student_auth_user_id INTEGER NOT NULL,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(class_id, student_auth_user_id)
);

-- =============================================================================
-- CLASS ASSIGNMENTS (teacher-created quests pinned to class)
-- =============================================================================
CREATE TABLE IF NOT EXISTS campaign_class_assignments (
    id SERIAL PRIMARY KEY,
    class_id INTEGER NOT NULL REFERENCES campaign_classes(id) ON DELETE CASCADE,
    quest_id VARCHAR(100) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    due_date TIMESTAMPTZ,
    created_by_auth_user_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- ASSIGNMENT COMPLETION TRACKING
-- =============================================================================
CREATE TABLE IF NOT EXISTS campaign_assignment_completions (
    id SERIAL PRIMARY KEY,
    assignment_id INTEGER NOT NULL REFERENCES campaign_class_assignments(id) ON DELETE CASCADE,
    student_auth_user_id INTEGER NOT NULL,
    completed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(assignment_id, student_auth_user_id)
);

-- =============================================================================
-- SESSION REPORTS (auto-generated by teacher layer)
-- =============================================================================
CREATE TABLE IF NOT EXISTS campaign_session_reports (
    id SERIAL PRIMARY KEY,
    class_id INTEGER NOT NULL REFERENCES campaign_classes(id) ON DELETE CASCADE,
    report_json JSONB NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- CUSTOM QUESTS (created via campaign editor)
-- =============================================================================
CREATE TABLE IF NOT EXISTS campaign_custom_quests (
    id SERIAL PRIMARY KEY,
    quest_id VARCHAR(100) NOT NULL UNIQUE,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    quest_type VARCHAR(30) NOT NULL,
    target_npc_id VARCHAR(100),
    l2p_quiz_set_id INTEGER,
    objectives JSONB NOT NULL DEFAULT '[]'::jsonb,
    rewards JSONB NOT NULL DEFAULT '{}'::jsonb,
    prerequisites JSONB DEFAULT '[]'::jsonb,
    audience VARCHAR(20) NOT NULL DEFAULT 'public' CHECK (audience IN ('public', 'class', 'private')),
    class_id INTEGER REFERENCES campaign_classes(id),
    created_by_auth_user_id INTEGER NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- MIGRATION TRACKING
-- =============================================================================
INSERT INTO schema_migrations (version, description) VALUES
    ('20260324_000004_campaign_social', 'Penpal, teacher classes, assignments, session reports, custom quests')
ON CONFLICT (version) DO NOTHING;
