apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: korczewski-services

labels:
  - pairs:
      app.kubernetes.io/part-of: korczewski
      app.kubernetes.io/component: assetgenerator
      tier: services

resources:
  - pv-audio.yaml
  - pv-visual.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - gpu-waker-deployment.yaml
  - gpu-waker-scaledobject.yaml
