---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assetgenerator-audio
  namespace: korczewski-services
  labels:
    app: assetgenerator
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: assetgenerator-audio-pv
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assetgenerator-visual
  namespace: korczewski-services
  labels:
    app: assetgenerator
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: assetgenerator-visual-pv
  resources:
    requests:
      storage: 50Gi
