apiVersion: v1
kind: ConfigMap
metadata:
  name: jitsi-config
  namespace: korczewski-jitsi
data:
  XMPP_DOMAIN: "meet.internal"
  XMPP_AUTH_DOMAIN: "auth.meet.internal"
  XMPP_GUEST_DOMAIN: "guest.meet.internal"
  XMPP_MUC_DOMAIN: "muc.meet.internal"
  XMPP_INTERNAL_MUC_DOMAIN: "internal-muc.meet.internal"
  XMPP_SERVER: "prosody.korczewski-jitsi.svc.cluster.local"
  XMPP_BOSH_URL_BASE: "http://prosody.korczewski-jitsi.svc.cluster.local:5280"
  PUBLIC_URL: "https://meet.korczewski.de"
  ENABLE_AUTH: "1"
  AUTH_TYPE: "jwt"
  JWT_APP_ID: "jitsi-meet"
  JWT_ACCEPTED_ISSUERS: "jitsi-meet"
  JWT_ACCEPTED_AUDIENCES: "jitsi-meet"
  JWT_ALLOW_EMPTY: "0"
  ENABLE_GUESTS: "1"
  TURN_ENABLE: "1"
  TURN_HOST: "meet.korczewski.de"
  TURN_PORT: "3478"
  TURNS_HOST: "meet.korczewski.de"
  TURNS_PORT: "5349"
  TURN_TRANSPORT: "tcp"
  TURN_CREDENTIAL_TYPE: "authSecret"
  JVB_AUTH_USER: "jvb"
  JVB_PORT: "10000"
  JVB_ENABLE_APIS: "rest,colibri"
  COLIBRI_REST_ENABLED: "true"
  JVB_TCP_HARVESTER_DISABLED: "true"
  JVB_ADVERTISE_PRIVATE_CANDIDATES: "false"
  JVB_WS_DOMAIN: "meet.korczewski.de"
  JVB_WS_SERVER_ID: "jvb.meet.korczewski.de"
  JICOFO_AUTH_USER: "focus"
  DISABLE_HTTPS: "1"
  ENABLE_LETSENCRYPT: "0"
  TZ: "Europe/Berlin"
  TOKEN_AUTH_URL: "https://auth.korczewski.de/api/jitsi/authorize?redirect_uri=https://meet.korczewski.de/{room}"
