
import base64
import os

# Minimal silent MP3 (about 0.1s)
SILENT_MP3_BASE64 = (
    "//uQZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWGluZyAAAAbAAAAEAAADAwMDAwMDAwMDAwMDAwMDAwMDAwMDA"
    "wMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw"
    "MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwM"
    "DAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMD"
    "AwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA"
    "wMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw"
    "MDAwMDAwMDAwMDAwAwAAAKIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIA"
    "AAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIA"
    "AAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIA"
    "AAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIA"
    "AAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIA"
    "AAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIA"
    "AAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIA"
    "AAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIA"
    "AAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIA"
    "AAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApMIAAAAApNREMy45OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
)

audio_files = [
    'correct1.mp3', 'correct2.mp3', 'correct3.mp3', 'correct4.mp3', 'correct5.mp3',
    'wrong.mp3', 'button-click.mp3', 'button-hover.mp3', 'modal-open.mp3', 'modal-close.mp3',
    'player-join.mp3', 'player-leave.mp3', 'timer-warning.mp3', 'timer-urgent.mp3',
    'applause.mp3', 'high-score.mp3', 'perfect-score.mp3', 'game-start.mp3', 'game-end.mp3',
    'question-start.mp3', 'lobby-created.mp3', 'lobby-joined.mp3', 'lobby-music.mp3',
    'notification.mp3', 'success.mp3', 'error.mp3', 'tick.mp3', 'countdown.mp3',
    'multiplier-up.mp3', 'multiplier-reset.mp3', 'score-points.mp3', 'score-bonus.mp3',
    'menu-select.mp3', 'menu-confirm.mp3', 'menu-cancel.mp3', 'volume-change.mp3',
    'theme-change.mp3', 'language-change.mp3'
]

output_dir = '/home/patrick/projects/l2p/frontend/public/audio'
silent_data = base64.b64decode(SILENT_MP3_BASE64)

for filename in audio_files:
    file_path = os.path.join(output_dir, filename)
    with open(file_path, 'wb') as f:
        f.write(silent_data)
    print(f"Created {file_path}")
