apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # ESO operator installation
  - https://github.com/external-secrets/external-secrets/releases/download/v0.9.11/external-secrets.yaml
  # ClusterSecretStore + ExternalSecret definitions
  - config/secret-store.yaml
  - config/auth-external-secret.yaml
  - config/l2p-external-secret.yaml
  - config/shop-external-secret.yaml
  - config/videovault-external-secret.yaml
  - config/arena-backend-external-secret.yaml
  - config/assetgenerator-external-secret.yaml
  - config/postgres-external-secret.yaml
  - config/smb-infra-external-secret.yaml
  - config/smb-services-external-secret.yaml
  - config/ipv64-external-secret.yaml
