apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: assetgenerator-secrets
  namespace: korczewski-services
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: assetgenerator-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: assetgenerator
