apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: traefik-dashboard-auth
  namespace: korczewski-infra
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: traefik-dashboard-auth
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: traefik
