apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-root-token
  namespace: korczewski-infra
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vault-root-token
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: vault-root-token
