apiVersion: v1
kind: Service
metadata:
  name: jvb-http
  namespace: korczewski-jitsi
spec:
  selector:
    app: jvb
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
